<?php

// Translation of file /home/dennis/www/coscms/modules/system_backup/regenerate.php

$_COS_LANG_MODULE['system_backup_file_regenerated'] = 'System backup genskabt';
$_COS_LANG_MODULE['system_backup_file_regenerated_failed'] = 'System backup genskabelse fejlede';
$_COS_LANG_MODULE['system_backup_regenerate'] = 'Genskab system fra backup';
$_COS_LANG_MODULE['system_backup_regenerate_confirm'] = 'Bekræft genskabelse af system backup';

// Translation of file /home/dennis/www/coscms/modules/system_backup/model.system_backup.inc

$_COS_LANG_MODULE['system_backup_dir_not_exists'] = 'System backup dir eksisterer ikke';
$_COS_LANG_MODULE['system_backup_dir_created'] = 'System backup dir er skabt';
$_COS_LANG_MODULE['system_backup_dir_could_not_be_created'] = 'System backup dir kunne ikke skabes';
$_COS_LANG_MODULE['system_backup_regenerate'] = 'Genskab system backup';
$_COS_LANG_MODULE['system_backup_delete'] = 'Slet system backup';

// Translation of file /home/dennis/www/coscms/modules/system_backup/create.php

$_COS_LANG_MODULE['system_backup_success'] = 'System backup er genskabt';
$_COS_LANG_MODULE['system_backup_failure'] = 'System backup kunne ikke genskabes';
$_COS_LANG_MODULE['system_backup_info'] = 'Skab system backup';
$_COS_LANG_MODULE['system_backup_backup'] = 'Backup dit system';

// Translation of file /home/dennis/www/coscms/modules/system_backup/delete.php

$_COS_LANG_MODULE['system_backup_file_deleted'] = 'System backup fil er slettet';
$_COS_LANG_MODULE['system_backup_file_deleted_failed'] = 'Sletelse af system backup fejlede';
$_COS_LANG_MODULE['system_backup_delete'] = 'Slet system backup';
$_COS_LANG_MODULE['system_backup_delete_confirm'] = 'Bekræft slettelse af system backup';

$_COS_LANG_MODULE['system_backup_timestamp_format'] = "åååå-mm-dd tt:mm:ss";

$_COS_LANG_MODULE['system_backup_limit_reached'] = 'Desværre ikke plads til flere backups';


