<?php

// Translation of file /home/dennis/www/coscms/modules/system_backup/regenerate.php

$_COS_LANG_MODULE['system_backup_file_regenerated'] = 'System backup has been regenerated';
$_COS_LANG_MODULE['system_backup_file_regenerated_failed'] = 'System regeneration Failed';
$_COS_LANG_MODULE['system_backup_delete'] = 'Delete System Backup Delete';
$_COS_LANG_MODULE['system_backup_regenerate_confirm'] = 'Confirm Regeneration of Backup';

// Translation of file /home/dennis/www/coscms/modules/system_backup/model.system_backup.inc

$_COS_LANG_MODULE['system_backup_dir_not_exists'] = 'System Backup Dir does Not exists';
$_COS_LANG_MODULE['system_backup_dir_created'] = 'System backup dir has been created';
$_COS_LANG_MODULE['system_backup_dir_could_not_be_created'] = 'System backup dir could not be created';
$_COS_LANG_MODULE['system_backup_regenerate'] = 'Regenerate System Backup';
$_COS_LANG_MODULE['system_backup_delete'] = 'Delete backup';

// Translation of file /home/dennis/www/coscms/modules/system_backup/create.php

$_COS_LANG_MODULE['system_backup_success'] = 'System Backup Success';
$_COS_LANG_MODULE['system_backup_failure'] = 'System Backup Failure';
$_COS_LANG_MODULE['system_backup_info'] = 'System Backup Info';
$_COS_LANG_MODULE['system_backup_backup'] = 'Backup System';

// Translation of file /home/dennis/www/coscms/modules/system_backup/delete.php

$_COS_LANG_MODULE['system_backup_file_deleted'] = 'System Backup File Deleted';
$_COS_LANG_MODULE['system_backup_file_deleted_failed'] = 'System Backup Delete File Failed';
$_COS_LANG_MODULE['system_backup_delete'] = 'Delete System Backup';
$_COS_LANG_MODULE['system_backup_delete_confirm'] = 'Confirm System Backup Delete';

$_COS_LANG_MODULE['system_backup_timestamp_format'] = "yyyy-mm-dd tt:mm:ss";

$_COS_LANG_MODULE['system_backup_limit_reached'] = 'system_backup_limit_reached';






